CREATE TABLE payment_proofs
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id        BIGINT       NOT NULL REFERENCES receipts (id) ON DELETE CASCADE,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename   VARCHAR(255) NOT NULL UNIQUE,
    file_type         VARCHAR(10)  NOT NULL,
    attached_at       DATE         NOT NULL
);

CREATE INDEX idx_payment_proofs_receipt_id ON payment_proofs (receipt_id);
