CREATE TABLE addresses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep          VARCHAR(8)   NOT NULL,
    address      VARCHAR(150) NOT NULL,
    number       VARCHAR(10)  NOT NULL,
    complement   VARCHAR(100),
    neighborhood VARCHAR(100) NOT NULL,
    city         VARCHAR(100) NOT NULL,
    state        VARCHAR(2)   NOT NULL
);

CREATE TABLE physical_persons (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(99)  NOT NULL,
    nationality    VARCHAR(19)  NOT NULL,
    civil_state    VARCHAR(20)  NOT NULL,
    occupation     VARCHAR(19)  NOT NULL,
    cpf            VARCHAR(11)  NOT NULL UNIQUE,
    id_card_number VARCHAR(19)  NOT NULL,
    address_id     BIGINT       NOT NULL REFERENCES addresses(id)
);

CREATE TABLE juridical_persons (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corporate_name    VARCHAR(99) NOT NULL,
    cnpj              VARCHAR(14) NOT NULL UNIQUE,
    representative_id BIGINT      NOT NULL REFERENCES physical_persons(id),
    address_id        BIGINT      NOT NULL REFERENCES addresses(id)
);

CREATE TABLE properties (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    type       VARCHAR(255) NOT NULL,
    purpose    VARCHAR(20)  NOT NULL,
    rent       INT          NOT NULL,
    cemig      VARCHAR(255) NOT NULL,
    copasa     VARCHAR(255) NOT NULL,
    iptu       VARCHAR(255) NOT NULL,
    address_id BIGINT       NOT NULL REFERENCES addresses(id)
);

CREATE TABLE payment_accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank           VARCHAR(255) NOT NULL,
    bank_branch    VARCHAR(255) NOT NULL,
    account_number VARCHAR(255) NOT NULL,
    pix_key        VARCHAR(255)
);

CREATE TABLE contracts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date         DATE        NOT NULL,
    duration           VARCHAR(20) NOT NULL,
    payment_day        INT         NOT NULL,
    payment_account_id BIGINT      NOT NULL REFERENCES payment_accounts(id),
    property_id        BIGINT      NOT NULL REFERENCES properties(id),
    landlord_id        BIGINT      NOT NULL,
    landlord_type      VARCHAR(10) NOT NULL
);

CREATE TABLE contract_tenants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT      NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
    tenant_id   BIGINT      NOT NULL,
    tenant_type VARCHAR(10) NOT NULL
);

CREATE TABLE receipts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date           DATE   NOT NULL,
    interval_start DATE   NOT NULL,
    interval_end   DATE   NOT NULL,
    discount       INT    NOT NULL DEFAULT 0,
    fine           INT    NOT NULL DEFAULT 0,
    contract_id    BIGINT NOT NULL REFERENCES contracts(id)
);

CREATE TABLE configs (
                         id                    BIGINT      PRIMARY KEY CHECK (id = 1),
                         default_landlord_id   BIGINT      NULL,
                         default_landlord_type VARCHAR(10) NULL
);

INSERT INTO configs (id, default_landlord_id, default_landlord_type) VALUES (1, NULL, NULL);
