CREATE TABLE contract_guarantors (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id    BIGINT      NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
    guarantor_id   BIGINT      NOT NULL,
    guarantor_type VARCHAR(10) NOT NULL
);

CREATE TABLE contract_witnesses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id  BIGINT      NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
    witness_id   BIGINT      NOT NULL,
    witness_type VARCHAR(10) NOT NULL
);
